site_name: Test
site_url: https://gothic-modding-community.github.io/gmc/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
    - content.code.copy
    - content.action.edit
    - content.action.view

nav:
  - Home:
    - index.md

  - Subsite:
    - subsite/index.md

plugins:
  - search
  - i18n: # TODO optimize local usage to build page based on environmental variables
      default_language: en
      languages:
        en:
          name: en - English
          build: true
        pl:
          name: pl - Polski
          build: true
      material_alternate: true
      nav_translations: # Only 1 global scope, if 2 nav elements are named the same, input translation only once
        pl:
          Home: Strona Główna
          Subsite: Podstrona
